# Generated by Django 5.2 on 2025-05-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(db_table='artist_type', related_name='artists', to='catalogue.type'),
        ),
    ]
