# Generated by Django 5.2 on 2025-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='name',
        ),
        migrations.AddField(
            model_name='artist',
            name='firstname',
            field=models.CharField(default='Anonyme', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='lastname',
            field=models.CharField(default='Test', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artists',
        ),
    ]
