# Generated by Django 5.2 on 2025-05-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_remove_artist_birth_date_remove_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'permissions': [('can_delete', 'Can delete artist')]},
        ),
    ]
