# Generated by Django 5.2 on 2025-05-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_artist_options_artist_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='prices',
            field=models.ManyToManyField(db_table='show_price', related_name='shows', to='catalogue.price'),
        ),
    ]
