# Generated by Django 5.2 on 2025-05-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_show_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRepresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representation_reservations', to='catalogue.representation')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_representations', to='catalogue.reservation')),
            ],
            options={
                'db_table': 'reservation_representation',
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='representations',
            field=models.ManyToManyField(related_name='reservations', through='catalogue.ReservationRepresentation', to='catalogue.representation'),
        ),
    ]
