# Generated by Django 5.2 on 2025-05-10 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_artist_types_artisttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
        migrations.AddField(
            model_name='artist',
            name='types',
            field=models.ManyToManyField(related_name='artists', through='catalogue.ArtistType', to='catalogue.type'),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='artist_types', to='catalogue.artist'),
        ),
        migrations.AlterField(
            model_name='artisttype',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='artist_types', to='catalogue.type'),
        ),
    ]
